const UNSPLASH_API_KEY = "uq_ad2eH1y4LjziHL50dLDv8h1esiKtEUNejDcwEOgw";
// const YOUTUBE_API_KEY = "AIzaSyDCh4pDvYFVJe5Lu_DbHT_kBgrJma83FxI";
// const YOUTUBE_API_KEY = "AIzaSyCjjqjn7wqsKm5EcKn-n3gMJgcl3-iOlpc";
const YOUTUBE_API_KEY = "AIzaSyBhd4f7KxGoXeR5HHXUZeYm5e5JHmS35Ws";
const OPEN_AI_KEY = "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";
exports.UNSPLASH_API_KEY = UNSPLASH_API_KEY;
exports.YOUTUBE_API_KEY = YOUTUBE_API_KEY;
exports.OPEN_AI_KEY = OPEN_AI_KEY;
